# [source.crates-io]
# replace-with = 'rsproxy-sparse'
# [source.rsproxy]
# registry = "https://rsproxy.cn/crates.io-index"
# [source.rsproxy-sparse]
# registry = "sparse+https://rsproxy.cn/index/"
# [registries.rsproxy]
# index = "https://rsproxy.cn/crates.io-index"

[net]
retry = 10
git-fetch-with-cli = true

[http]
timeout = 600
multiplexing = false

# 如果你走代理（按你的实际改）
# socks5h 会让 DNS 也走代理，通常更稳
proxy = "socks5h://127.0.0.1:10808"
# 或 http 代理
#proxy = "http://127.0.0.1:10808"

# 如果你的 cargo 支持这俩字段（新版本一般支持）
low-speed-limit = 1
# low-speed-time = 600